fix .faicon generation
.favicon will not be generated when using an NON PREMIUM shodan token.
Cause  wfavUp.py will throw an error 
``` .js 
shodan.exception.APIError: Please upgrade your API plan to use filters or paging.
```